version: '3'
services:
  web:
    build: .
    image: sirixdb/sirix
    ports:
      - "9443:9443"
    volumes:
      - /opt/intrexx
    depends_on:
      - keycloak
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG