version: '3'
services:
  web:
    build: .
    ports:
      - "9443:9443"
    volumes:
      - /opt/intrexx
    depends_on:
      - keycloak
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    KEYCLOAK_URL=http://localhost:8080/auth
    KEYCLOAK_USER: admin
    KEYCLOAK_PASSWORD: admin
    KEYCLOAK_IMPORT:
    volumes:
      - C:\logs\keycloak:/usr/app/logs
      - C:\settings:/etc/settings
  networks:
    keycloak:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.0.0.0/16

