version: '3'
services:
  waitforkeycloak:
    image: dadarek/wait-for-dependencies
    depends_on:
      - keycloak
    command: keycloak:8080
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
  web:
    build: .
    image: sirixdb/sirix
    ports:
      - "9443:9443"
    volumes:
      - /opt/intrexx
    depends_on:
      - waitforkeycloak
