services:
  - docker
language: java
jdk:
  - oraclejdk9
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      name: "OracleJDK 9"
      jdk: oraclejdk9
      script: mvn -q clean verify -B
    - if: type != pull_request
      name: "OpenJDK 11"
      jdk: openjdk11
      script: mvn -q clean verify -B
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request AND env(SONATYPE_NEXUS_USERNAME) IS present
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    on_failure: always
    recipients:
      - lichtenberger.johannes@gmail.com
after-success:
  mvn jacoco:report coveralls:jacoco
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
