services:
  - docker
language: java
jdk:
  - oraclejdk9
branches:
  only:
    - master
notifications:
  email:
    on_failure: always
    recipients:
      - lichtenberger.johannes@gmail.com
after-success:
  mvn jacoco:report coveralls:jacoco
before_install:
  - docker build -t sirixdb/sirix ./bundles/sirix-rest-api/src/main/docker
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
