language: java
jdk:
  - oraclejdk9
branches:
  only:
    - master
notifications:
  email:
    on_failure: always
    recipients:
      - lichtenberger.johannes@gmail.com
gemfile: Gemfile
after-success:
  mvn jacoco:report coveralls:jacoco
