services:
  - docker
language: java
jdk:
  - openjdk13
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      name: "OpenJDK 13"
      jdk: openjdk13
      script: ./gradlew clean build
notifications:
  email:
    on_failure: always
    recipients:
      - kuttibalaji.v6@gmail.com
after-success:
  ./gradlew jacocoTestReport coveralls
